# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import legal_pb2 as legal__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in legal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LegalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLawyer = channel.unary_unary(
                '/baixing.legal.LegalService/GetLawyer',
                request_serializer=legal__pb2.GetLawyerRequest.SerializeToString,
                response_deserializer=legal__pb2.LawyerResponse.FromString,
                _registered_method=True)
        self.BatchGetLawyers = channel.unary_unary(
                '/baixing.legal.LegalService/BatchGetLawyers',
                request_serializer=legal__pb2.BatchGetLawyersRequest.SerializeToString,
                response_deserializer=legal__pb2.BatchLawyersResponse.FromString,
                _registered_method=True)
        self.SearchLawyers = channel.unary_unary(
                '/baixing.legal.LegalService/SearchLawyers',
                request_serializer=legal__pb2.SearchLawyersRequest.SerializeToString,
                response_deserializer=legal__pb2.SearchLawyersResponse.FromString,
                _registered_method=True)
        self.GetLawyerSchedule = channel.unary_unary(
                '/baixing.legal.LegalService/GetLawyerSchedule',
                request_serializer=legal__pb2.GetLawyerScheduleRequest.SerializeToString,
                response_deserializer=legal__pb2.LawyerScheduleResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/baixing.legal.LegalService/CheckAvailability',
                request_serializer=legal__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=legal__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)
        self.GetLawyerStats = channel.unary_unary(
                '/baixing.legal.LegalService/GetLawyerStats',
                request_serializer=legal__pb2.GetLawyerStatsRequest.SerializeToString,
                response_deserializer=legal__pb2.LawyerStatsResponse.FromString,
                _registered_method=True)
        self.GetConsultation = channel.unary_unary(
                '/baixing.legal.LegalService/GetConsultation',
                request_serializer=legal__pb2.GetConsultationRequest.SerializeToString,
                response_deserializer=legal__pb2.ConsultationResponse.FromString,
                _registered_method=True)
        self.GetUserConsultations = channel.unary_unary(
                '/baixing.legal.LegalService/GetUserConsultations',
                request_serializer=legal__pb2.GetUserConsultationsRequest.SerializeToString,
                response_deserializer=legal__pb2.UserConsultationsResponse.FromString,
                _registered_method=True)
        self.GetAppointment = channel.unary_unary(
                '/baixing.legal.LegalService/GetAppointment',
                request_serializer=legal__pb2.GetAppointmentRequest.SerializeToString,
                response_deserializer=legal__pb2.AppointmentResponse.FromString,
                _registered_method=True)
        self.GetUserAppointments = channel.unary_unary(
                '/baixing.legal.LegalService/GetUserAppointments',
                request_serializer=legal__pb2.GetUserAppointmentsRequest.SerializeToString,
                response_deserializer=legal__pb2.UserAppointmentsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/baixing.legal.LegalService/HealthCheck',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=legal__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class LegalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLawyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetLawyers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchLawyers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLawyerSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLawyerStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsultation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserConsultations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppointment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAppointments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LegalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLawyer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLawyer,
                    request_deserializer=legal__pb2.GetLawyerRequest.FromString,
                    response_serializer=legal__pb2.LawyerResponse.SerializeToString,
            ),
            'BatchGetLawyers': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetLawyers,
                    request_deserializer=legal__pb2.BatchGetLawyersRequest.FromString,
                    response_serializer=legal__pb2.BatchLawyersResponse.SerializeToString,
            ),
            'SearchLawyers': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchLawyers,
                    request_deserializer=legal__pb2.SearchLawyersRequest.FromString,
                    response_serializer=legal__pb2.SearchLawyersResponse.SerializeToString,
            ),
            'GetLawyerSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLawyerSchedule,
                    request_deserializer=legal__pb2.GetLawyerScheduleRequest.FromString,
                    response_serializer=legal__pb2.LawyerScheduleResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=legal__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=legal__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
            'GetLawyerStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLawyerStats,
                    request_deserializer=legal__pb2.GetLawyerStatsRequest.FromString,
                    response_serializer=legal__pb2.LawyerStatsResponse.SerializeToString,
            ),
            'GetConsultation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsultation,
                    request_deserializer=legal__pb2.GetConsultationRequest.FromString,
                    response_serializer=legal__pb2.ConsultationResponse.SerializeToString,
            ),
            'GetUserConsultations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserConsultations,
                    request_deserializer=legal__pb2.GetUserConsultationsRequest.FromString,
                    response_serializer=legal__pb2.UserConsultationsResponse.SerializeToString,
            ),
            'GetAppointment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppointment,
                    request_deserializer=legal__pb2.GetAppointmentRequest.FromString,
                    response_serializer=legal__pb2.AppointmentResponse.SerializeToString,
            ),
            'GetUserAppointments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAppointments,
                    request_deserializer=legal__pb2.GetUserAppointmentsRequest.FromString,
                    response_serializer=legal__pb2.UserAppointmentsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=legal__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'baixing.legal.LegalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('baixing.legal.LegalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LegalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLawyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/GetLawyer',
            legal__pb2.GetLawyerRequest.SerializeToString,
            legal__pb2.LawyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetLawyers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/BatchGetLawyers',
            legal__pb2.BatchGetLawyersRequest.SerializeToString,
            legal__pb2.BatchLawyersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchLawyers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/SearchLawyers',
            legal__pb2.SearchLawyersRequest.SerializeToString,
            legal__pb2.SearchLawyersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLawyerSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/GetLawyerSchedule',
            legal__pb2.GetLawyerScheduleRequest.SerializeToString,
            legal__pb2.LawyerScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/CheckAvailability',
            legal__pb2.CheckAvailabilityRequest.SerializeToString,
            legal__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLawyerStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/GetLawyerStats',
            legal__pb2.GetLawyerStatsRequest.SerializeToString,
            legal__pb2.LawyerStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsultation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/GetConsultation',
            legal__pb2.GetConsultationRequest.SerializeToString,
            legal__pb2.ConsultationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserConsultations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/GetUserConsultations',
            legal__pb2.GetUserConsultationsRequest.SerializeToString,
            legal__pb2.UserConsultationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAppointment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/GetAppointment',
            legal__pb2.GetAppointmentRequest.SerializeToString,
            legal__pb2.AppointmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserAppointments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/GetUserAppointments',
            legal__pb2.GetUserAppointmentsRequest.SerializeToString,
            legal__pb2.UserAppointmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.legal.LegalService/HealthCheck',
            common__pb2.Empty.SerializeToString,
            legal__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
