# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import user_pb2 as user__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/baixing.user.UserService/GetUser',
                request_serializer=user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=user__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.GetUserProfile = channel.unary_unary(
                '/baixing.user.UserService/GetUserProfile',
                request_serializer=user__pb2.GetUserProfileRequest.SerializeToString,
                response_deserializer=user__pb2.UserProfile.FromString,
                _registered_method=True)
        self.UpdateUserStatus = channel.unary_unary(
                '/baixing.user.UserService/UpdateUserStatus',
                request_serializer=user__pb2.UpdateUserStatusRequest.SerializeToString,
                response_deserializer=common__pb2.Empty.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/baixing.user.UserService/ValidateToken',
                request_serializer=user__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=user__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.GetUserQuota = channel.unary_unary(
                '/baixing.user.UserService/GetUserQuota',
                request_serializer=user__pb2.GetUserQuotaRequest.SerializeToString,
                response_deserializer=user__pb2.UserQuota.FromString,
                _registered_method=True)
        self.GetLawyer = channel.unary_unary(
                '/baixing.user.UserService/GetLawyer',
                request_serializer=user__pb2.GetLawyerRequest.SerializeToString,
                response_deserializer=user__pb2.Lawyer.FromString,
                _registered_method=True)
        self.GetLawyerSchedule = channel.unary_unary(
                '/baixing.user.UserService/GetLawyerSchedule',
                request_serializer=user__pb2.GetLawyerScheduleRequest.SerializeToString,
                response_deserializer=user__pb2.LawyerSchedule.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLawyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLawyerSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=user__pb2.GetUserRequest.FromString,
                    response_serializer=user__pb2.GetUserResponse.SerializeToString,
            ),
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=user__pb2.GetUserProfileRequest.FromString,
                    response_serializer=user__pb2.UserProfile.SerializeToString,
            ),
            'UpdateUserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserStatus,
                    request_deserializer=user__pb2.UpdateUserStatusRequest.FromString,
                    response_serializer=common__pb2.Empty.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=user__pb2.ValidateTokenRequest.FromString,
                    response_serializer=user__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'GetUserQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserQuota,
                    request_deserializer=user__pb2.GetUserQuotaRequest.FromString,
                    response_serializer=user__pb2.UserQuota.SerializeToString,
            ),
            'GetLawyer': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLawyer,
                    request_deserializer=user__pb2.GetLawyerRequest.FromString,
                    response_serializer=user__pb2.Lawyer.SerializeToString,
            ),
            'GetLawyerSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLawyerSchedule,
                    request_deserializer=user__pb2.GetLawyerScheduleRequest.FromString,
                    response_serializer=user__pb2.LawyerSchedule.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'baixing.user.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('baixing.user.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.user.UserService/GetUser',
            user__pb2.GetUserRequest.SerializeToString,
            user__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.user.UserService/GetUserProfile',
            user__pb2.GetUserProfileRequest.SerializeToString,
            user__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.user.UserService/UpdateUserStatus',
            user__pb2.UpdateUserStatusRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.user.UserService/ValidateToken',
            user__pb2.ValidateTokenRequest.SerializeToString,
            user__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.user.UserService/GetUserQuota',
            user__pb2.GetUserQuotaRequest.SerializeToString,
            user__pb2.UserQuota.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLawyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.user.UserService/GetLawyer',
            user__pb2.GetLawyerRequest.SerializeToString,
            user__pb2.Lawyer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLawyerSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/baixing.user.UserService/GetLawyerSchedule',
            user__pb2.GetLawyerScheduleRequest.SerializeToString,
            user__pb2.LawyerSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
