{{- range $name, $svc := .Values.microservices }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baixing-assistant.fullname" $ }}-{{ $name }}-config
  labels:
{{ include "baixing-assistant.labels" $ | indent 4 }}
    app.kubernetes.io/component: {{ $name }}
data:
{{ toYaml ( $svc.config | default dict ) | indent 2 }}
{{- end }}
{{- end }}
