"""add_consultation_columns

Revision ID: z9y8x7w6v5u4
Revises: t2u3v4w5x6y7
Create Date: 2026-02-09 00:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'z9y8x7w6v5u4'
down_revision: Union[str, None] = 't2u3v4w5x6y7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add columns to consultations table
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), server_default='general', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('message_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('total_tokens', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_transferred', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('transferred_to', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transfer_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('archive_reason', sa.String(length=200), nullable=True))
        batch_op.create_index('ix_consultations_category', ['category'], unique=False)
        batch_op.create_index('ix_consultations_status', ['status'], unique=False)
        batch_op.create_index('ix_consultations_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_foreign_key('fk_consultations_transferred_to_users', 'users', ['transferred_to'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop consultations columns
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_consultations_transferred_to_users', type_='foreignkey')
        batch_op.drop_index('ix_consultations_user_created')
        batch_op.drop_index('ix_consultations_status')
        batch_op.drop_index('ix_consultations_category')
        batch_op.drop_column('archive_reason')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('transfer_reason')
        batch_op.drop_column('transferred_to')
        batch_op.drop_column('transferred_at')
        batch_op.drop_column('is_transferred')
        batch_op.drop_column('total_tokens')
        batch_op.drop_column('message_count')
        batch_op.drop_column('status')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
