"""错误码规范

提供统一的错误码定义，确保所有接口使用一致的错误码。
"""
class ErrorCode:
    """错误码规范
    
    错误码格式：模块_错误类型_具体错误
    例如：USER_NOT_FOUND, PAYMENT_AMOUNT_MISMATCH
    """
    
    # 通用错误码 (1xxx)
    SUCCESS = "SUCCESS"
    INVALID_REQUEST = "INVALID_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    
    # 用户错误码 (2xxx)
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    EMAIL_VERIFICATION_REQUIRED = "EMAIL_VERIFICATION_REQUIRED"
    PHONE_VERIFICATION_REQUIRED = "PHONE_VERIFICATION_REQUIRED"
    
    # 支付错误码 (3xxx)
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_AMOUNT_MISMATCH = "PAYMENT_AMOUNT_MISMATCH"
    PAYMENT_ORDER_NOT_FOUND = "PAYMENT_ORDER_NOT_FOUND"
    PAYMENT_ORDER_ALREADY_PAID = "PAYMENT_ORDER_ALREADY_PAID"
    PAYMENT_ORDER_CANCELLED = "PAYMENT_ORDER_CANCELLED"
    PAYMENT_CALLBACK_INVALID = "PAYMENT_CALLBACK_INVALID"
    PAYMENT_CALLBACK_DUPLICATE = "PAYMENT_CALLBACK_DUPLICATE"
    PAYMENT_METHOD_NOT_SUPPORTED = "PAYMENT_METHOD_NOT_SUPPORTED"
    PAYMENT_PROCESSING_ERROR = "PAYMENT_PROCESSING_ERROR"
    PAYMENT_TIMEOUT = "PAYMENT_TIMEOUT"
    
    # AI错误码 (4xxx)
    AI_SERVICE_UNAVAILABLE = "AI_SERVICE_UNAVAILABLE"
    AI_QUOTA_EXCEEDED = "AI_QUOTA_EXCEEDED"
    AI_REQUEST_TOO_LONG = "AI_REQUEST_TOO_LONG"
    AI_RESPONSE_INVALID = "AI_RESPONSE_INVALID"
    AI_TIMEOUT = "AI_TIMEOUT"
    AI_RATE_LIMIT_EXCEEDED = "AI_RATE_LIMIT_EXCEEDED"
    
    # 业务错误码 (5xxx)
    INVALID_ORDER_TYPE = "INVALID_ORDER_TYPE"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    ORDER_EXPIRED = "ORDER_EXPIRED"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    
    # 内容错误码 (6xxx)
    CONTENT_NOT_FOUND = "CONTENT_NOT_FOUND"
    CONTENT_ALREADY_PUBLISHED = "CONTENT_ALREADY_PUBLISHED"
    CONTENT_MODIFICATION_NOT_ALLOWED = "CONTENT_MODIFICATION_NOT_ALLOWED"
    CONTENT_VALIDATION_FAILED = "CONTENT_VALIDATION_FAILED"
    
    # 论坛错误码 (7xxx)
    FORUM_POST_NOT_FOUND = "FORUM_POST_NOT_FOUND"
    FORUM_COMMENT_NOT_FOUND = "FORUM_COMMENT_NOT_FOUND"
    FORUM_POST_LOCKED = "FORUM_POST_LOCKED"
    FORUM_COMMENT_NOT_ALLOWED = "FORUM_COMMENT_NOT_ALLOWED"
    
    # 系统错误码 (8xxx)
    SYSTEM_MAINTENANCE = "SYSTEM_MAINTENANCE"
    SYSTEM_OVERLOADED = "SYSTEM_OVERLOADED"
    DATABASE_ERROR = "DATABASE_ERROR"
    CACHE_ERROR = "CACHE_ERROR"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    
    # 限流错误码 (9xxx)
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    RATE_LIMIT_API_KEY = "RATE_LIMIT_API_KEY"
    RATE_LIMIT_IP = "RATE_LIMIT_IP"
    RATE_LIMIT_USER = "RATE_LIMIT_USER"


# 错误码映射表
ERROR_CODE_MESSAGES = {
    # 通用错误
    ErrorCode.SUCCESS: "操作成功",
    ErrorCode.INVALID_REQUEST: "请求参数无效",
    ErrorCode.UNAUTHORIZED: "未授权，请登录",
    ErrorCode.FORBIDDEN: "权限不足",
    ErrorCode.NOT_FOUND: "资源不存在",
    ErrorCode.INTERNAL_ERROR: "系统内部错误",
    
    # 用户错误
    ErrorCode.USER_NOT_FOUND: "用户不存在",
    ErrorCode.USER_ALREADY_EXISTS: "用户已存在",
    ErrorCode.INVALID_CREDENTIALS: "用户名或密码错误",
    ErrorCode.TOKEN_EXPIRED: "登录已过期，请重新登录",
    ErrorCode.TOKEN_INVALID: "无效的令牌",
    ErrorCode.EMAIL_VERIFICATION_REQUIRED: "需要验证邮箱",
    ErrorCode.PHONE_VERIFICATION_REQUIRED: "需要验证手机号",
    
    # 支付错误
    ErrorCode.PAYMENT_FAILED: "支付失败",
    ErrorCode.PAYMENT_AMOUNT_MISMATCH: "支付金额不匹配",
    ErrorCode.PAYMENT_ORDER_NOT_FOUND: "订单不存在",
    ErrorCode.PAYMENT_ORDER_ALREADY_PAID: "订单已支付",
    ErrorCode.PAYMENT_ORDER_CANCELLED: "订单已取消",
    ErrorCode.PAYMENT_CALLBACK_INVALID: "支付回调无效",
    ErrorCode.PAYMENT_CALLBACK_DUPLICATE: "重复的支付回调",
    ErrorCode.PAYMENT_METHOD_NOT_SUPPORTED: "不支持的支付方式",
    ErrorCode.PAYMENT_PROCESSING_ERROR: "支付处理错误",
    ErrorCode.PAYMENT_TIMEOUT: "支付超时",
    
    # AI错误
    ErrorCode.AI_SERVICE_UNAVAILABLE: "AI服务不可用",
    ErrorCode.AI_QUOTA_EXCEEDED: "AI配额已用完",
    ErrorCode.AI_REQUEST_TOO_LONG: "请求内容过长",
    ErrorCode.AI_RESPONSE_INVALID: "AI响应无效",
    ErrorCode.AI_TIMEOUT: "AI请求超时",
    ErrorCode.AI_RATE_LIMIT_EXCEEDED: "AI请求过于频繁",
    
    # 业务错误
    ErrorCode.INVALID_ORDER_TYPE: "无效的订单类型",
    ErrorCode.INSUFFICIENT_BALANCE: "余额不足",
    ErrorCode.ORDER_EXPIRED: "订单已过期",
    ErrorCode.RESOURCE_NOT_FOUND: "资源不存在",
    ErrorCode.RESOURCE_ALREADY_EXISTS: "资源已存在",
    ErrorCode.OPERATION_NOT_ALLOWED: "不允许的操作",
    ErrorCode.VALIDATION_ERROR: "参数验证失败",
    
    # 内容错误
    ErrorCode.CONTENT_NOT_FOUND: "内容不存在",
    ErrorCode.CONTENT_ALREADY_PUBLISHED: "内容已发布",
    ErrorCode.CONTENT_MODIFICATION_NOT_ALLOWED: "不允许修改内容",
    ErrorCode.CONTENT_VALIDATION_FAILED: "内容验证失败",
    
    # 论坛错误
    ErrorCode.FORUM_POST_NOT_FOUND: "帖子不存在",
    ErrorCode.FORUM_COMMENT_NOT_FOUND: "评论不存在",
    ErrorCode.FORUM_POST_LOCKED: "帖子已锁定",
    ErrorCode.FORUM_COMMENT_NOT_ALLOWED: "不允许评论",
    
    # 系统错误
    ErrorCode.SYSTEM_MAINTENANCE: "系统维护中",
    ErrorCode.SYSTEM_OVERLOADED: "系统负载过高",
    ErrorCode.DATABASE_ERROR: "数据库错误",
    ErrorCode.CACHE_ERROR: "缓存错误",
    ErrorCode.EXTERNAL_SERVICE_ERROR: "外部服务错误",
    
    # 限流错误
    ErrorCode.RATE_LIMIT_EXCEEDED: "请求过于频繁",
    ErrorCode.RATE_LIMIT_API_KEY: "API密钥限流",
    ErrorCode.RATE_LIMIT_IP: "IP限流",
    ErrorCode.RATE_LIMIT_USER: "用户限流",
}


def get_error_message(code: str) -> str:
    """获取错误码对应的错误消息
    
    Args:
        code: 错误码
    
    Returns:
        错误消息
    """
    return ERROR_CODE_MESSAGES.get(code, "未知错误")
